%% Code generated by libero. DO NOT EDIT.
%%
%% Pre-registers all constructor atoms that may appear in client ETF
%% payloads, so binary_to_term([safe]) can decode them without
%% rejecting unknown atoms.
%%
%% ensure/0 uses persistent_term as a one-shot guard so the
%% binary_to_atom calls only run once per VM lifetime.
%%
%% lists:foreach + fun is used instead of bare binary_to_atom calls
%% because the Erlang compiler optimizes away pure BIF calls whose
%% results are discarded.

-module(user_auth@generated@rpc_atoms).
-export([ensure/0]).

ensure() ->
    case persistent_term:get({?MODULE, done}, false) of
        true -> nil;
        false -> do_ensure()
    end.

do_ensure() ->
    lists:foreach(fun(B) -> binary_to_atom(B) end, [
        <<"database_error">>,
        <<"decode_error">>,
        <<"error">>,
        <<"false">>,
        <<"home">>,
        <<"internal_error">>,
        <<"item">>,
        <<"item_params">>,
        <<"malformed_request">>,
        <<"model">>,
        <<"navigate_to">>,
        <<"nil">>,
        <<"no_op">>,
        <<"none">>,
        <<"not_found">>,
        <<"ok">>,
        <<"session_expired">>,
        <<"sign_in">>,
        <<"sign_up">>,
        <<"some">>,
        <<"title_required">>,
        <<"true">>,
        <<"unknown_function">>,
        <<"user">>,
        <<"user_already_exists">>,
        <<"user_clicked_sign_in">>,
        <<"user_clicked_sign_out">>,
        <<"user_clicked_sign_up">>,
        <<"user_deleted">>,
        <<"user_not_found">>,
        <<"user_submitted_title">>,
        <<"user_toggled">>,
        <<"user_typed_title">>,
        <<"user_typed_username">>
    ]),
    persistent_term:put({?MODULE, done}, true),
    nil.
