//// Erlang atom pre-registration for generated wire codecs.

import gleam/list
import gleam/option
import gleam/string
import libero/walker.{type DiscoveredType}
import libero/wire_identity

pub fn generate(
  discovered discovered: List(DiscoveredType),
  atoms_module atoms_module: String,
  wire_module wire_module: option.Option(String),
) -> String {
  let framework_atoms = [
    "ok", "error", "some", "none", "nil", "true", "false", "malformed_request",
    "unknown_function", "internal_error", "decode_error",
  ]
  let variant_atoms =
    list.flat_map(discovered, fn(dt) {
      list.flat_map(dt.variants, fn(v) {
        let #(_sig, hash) =
          wire_identity.wire_identity(
            module_path: v.module_path,
            constructor_name: v.variant_name,
            fields: v.fields,
          )
        [walker.to_snake_case(v.variant_name), hash]
      })
    })
  let all_atoms =
    list.append(framework_atoms, variant_atoms)
    |> list.unique()
    |> list.sort(string.compare)
  let atom_list =
    list.map(all_atoms, fn(atom) { "        <<\"" <> atom <> "\">>" })
    |> string.join(",\n")

  "%% Code generated by libero. DO NOT EDIT.
%%
%% Pre-registers atoms that may appear in ETF payloads so
%% binary_to_term([safe]) can decode them without rejecting unknown atoms.
%%
%% ensure/0 uses persistent_term as a one-shot guard so the
%% binary_to_atom calls only run once per VM lifetime.

-module(" <> atoms_module <> ").
-export([ensure/0]).

ensure() ->
    case persistent_term:get({?MODULE, done}, false) of
        true -> nil;
        false -> do_ensure()
    end.

do_ensure() ->
    lists:foreach(fun(B) -> binary_to_atom(B) end, [
" <> atom_list <> "
    ]),
    " <> case wire_module {
    option.Some(mod) ->
      "persistent_term:put({libero, wire_module}, '" <> mod <> "'),\n    "
    option.None -> ""
  } <> "persistent_term:put({?MODULE, done}, true),
    nil.
"
}
