//// Tests for the per-consumer wire-transformers Erlang codegen.
////
//// Exact output shape is part of the wire-type-identity spec, but
//// these tests use targeted substring checks against the generated
//// source. That keeps them robust to whitespace and ordering changes
//// while still pinning the load-bearing properties: module shape,
//// per-type function pairs, hash-as-wire-tag, bare-atom-as-BEAM-tag,
//// float wrapping, list comprehensions, recursive cross-type calls.

import gleam/string
import libero/codegen_wire_erl
import libero/field_type.{
  BitArrayField, BoolField, DictOf, FloatField, IntField, ListOf, NilField,
  OptionOf, ResultOf, StringField, TupleOf, UserType,
}
import libero/walker.{type DiscoveredType, DiscoveredType, DiscoveredVariant}
import libero/wire_identity

// -- fixtures --------------------------------------------------------------

fn variant(
  module_path: String,
  name: String,
  fields: List(field_type.FieldType),
) -> walker.DiscoveredVariant {
  DiscoveredVariant(
    module_path: module_path,
    variant_name: name,
    atom_name: walker.qualified_atom_name(
      module_path: module_path,
      variant_name: name,
    ),
    float_field_indices: [],
    fields: fields,
  )
}

fn typ(
  module_path: String,
  name: String,
  variants: List(walker.DiscoveredVariant),
) -> DiscoveredType {
  DiscoveredType(
    module_path: module_path,
    type_name: name,
    type_params: [],
    variants: variants,
  )
}

fn hash_for(
  module_path: String,
  name: String,
  fields: List(field_type.FieldType),
) -> String {
  let #(_sig, hash) =
    wire_identity.wire_identity(
      module_path: module_path,
      constructor_name: name,
      fields: fields,
    )
  hash
}

// -- module shape ----------------------------------------------------------

pub fn empty_discovered_emits_module_with_only_float_helper_test() {
  let assert Ok(out) = codegen_wire_erl.generate(module_name: "x_wire", discovered: [])
  let assert True = string.contains(out, "-module(x_wire).")
  let assert True = string.contains(out, "encode_float/1")
  let assert True = string.contains(out, "encode_float(F) when is_float(F)")
}

pub fn header_marks_generated_test() {
  let assert Ok(out) = codegen_wire_erl.generate(module_name: "x_wire", discovered: [])
  let assert True =
    string.contains(out, "Code generated by libero. DO NOT EDIT.")
}

// -- single-variant record with primitives ---------------------------------

pub fn primitive_record_emits_encode_and_decode_test() {
  let dt =
    typ("shared/discount", "Discount", [
      variant("shared/discount", "Discount", [IntField, StringField, BoolField]),
    ])
  let hash = hash_for("shared/discount", "Discount", [
    IntField, StringField, BoolField,
  ])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])

  // Exports both directions for the type.
  let assert True =
    string.contains(out, "encode_shared_discount__discount/1")
  let assert True =
    string.contains(out, "decode_shared_discount__discount/1")

  // Encode clause: BEAM-shape pattern, wire-shape body.
  let assert True =
    string.contains(
      out,
      "encode_shared_discount__discount({discount, F0, F1, F2}) ->",
    )
  let assert True = string.contains(out, "{'" <> hash <> "', F0, F1, F2}")

  // Decode clause: wire-shape pattern, BEAM-shape body.
  let assert True =
    string.contains(
      out,
      "decode_shared_discount__discount({'" <> hash <> "', F0, F1, F2}) ->",
    )
  let assert True = string.contains(out, "{discount, F0, F1, F2}")
}

// -- float field wrapping (libero-3ccw regression) -------------------------

pub fn float_field_wraps_with_encode_float_on_encode_test() {
  let dt =
    typ("m", "Discount", [variant("m", "Discount", [IntField, FloatField])])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])
  let assert True = string.contains(out, "encode_float(F1)")
  // Decode side: Float passes through (BEAM ETF preserves Float natively).
  let assert True =
    string.contains(out, "decode_m__discount({'") && string.contains(out, ", F0, F1}) ->\n    {discount, F0, F1}")
}

// -- 0-arity variants ------------------------------------------------------

pub fn zero_arity_variant_emits_bare_atom_to_hash_test() {
  let dt =
    typ("shared/types", "Status", [
      variant("shared/types", "Pending", []),
      variant("shared/types", "Active", []),
    ])
  let pending_hash = hash_for("shared/types", "Pending", [])
  let active_hash = hash_for("shared/types", "Active", [])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])

  // Encode: bare atom -> hashed atom literal.
  let assert True =
    string.contains(
      out,
      "encode_shared_types__status(pending) ->\n    '" <> pending_hash <> "'",
    )
  let assert True =
    string.contains(
      out,
      "encode_shared_types__status(active) ->\n    '" <> active_hash <> "'",
    )

  // Decode: hashed atom literal -> bare atom.
  let assert True =
    string.contains(
      out,
      "decode_shared_types__status('" <> pending_hash <> "') ->\n    pending",
    )
}

// -- N-arity sum variants --------------------------------------------------

pub fn sum_type_n_arity_variants_emit_separate_clauses_test() {
  let dt =
    typ("m", "ItemError", [
      variant("m", "NotFound", [IntField]),
      variant("m", "InvalidState", [StringField]),
    ])
  let nf_hash = hash_for("m", "NotFound", [IntField])
  let is_hash = hash_for("m", "InvalidState", [StringField])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])

  let assert True =
    string.contains(
      out,
      "encode_m__item_error({not_found, F0}) ->\n    {'" <> nf_hash <> "', F0}",
    )
  let assert True =
    string.contains(
      out,
      "encode_m__item_error({invalid_state, F0}) ->\n    {'" <> is_hash <> "', F0}",
    )
}

// -- nested user types (envelope wrapping a List of records) ---------------

pub fn list_of_user_type_recurses_via_named_call_test() {
  let inner_type = UserType("admin/discounts", "Discount", [])
  let envelope_dt =
    typ("admin/discounts", "DiscountAdminData", [
      variant("admin/discounts", "DiscountAdminData", [ListOf(inner_type)]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [envelope_dt])

  // Encode side: list comprehension wrapping the recursive call.
  let assert True =
    string.contains(
      out,
      "[encode_admin_discounts__discount(_X0) || _X0 <- F0]",
    )
  // Decode side: same shape, decode_ instead of encode_.
  let assert True =
    string.contains(
      out,
      "[decode_admin_discounts__discount(_X0) || _X0 <- F0]",
    )
}

// -- Option / Result containers --------------------------------------------

pub fn option_of_user_type_pattern_matches_some_none_test() {
  let inner = UserType("m", "Item", [])
  let dt =
    typ("m", "Wrapper", [variant("m", "Wrapper", [OptionOf(inner)])])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])

  let assert True =
    string.contains(
      out,
      "case F0 of {some, _X0} -> {some, encode_m__item(_X0)}; none -> none end",
    )
}

pub fn result_of_user_type_pattern_matches_ok_error_test() {
  let dt =
    typ("m", "Resp", [
      variant("m", "Resp", [
        ResultOf(ok: UserType("m", "Item", []), err: StringField),
      ]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])

  let assert True =
    string.contains(
      out,
      "case F0 of {ok, _X0} -> {ok, encode_m__item(_X0)}; {error, _E0} -> {error, _E0} end",
    )
}

// -- Dict (only values transform) ------------------------------------------

pub fn dict_with_user_value_transforms_only_values_test() {
  let dt =
    typ("m", "Index", [
      variant("m", "Index", [DictOf(key: StringField, value: UserType("m", "Item", []))]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])

  let assert True =
    string.contains(
      out,
      "maps:map(fun(_K, _X0) -> encode_m__item(_X0) end, F0)",
    )
}

// -- containers of primitives skip the transformation --------------------

pub fn list_of_int_passes_through_test() {
  let dt =
    typ("m", "Bucket", [variant("m", "Bucket", [ListOf(IntField)])])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])
  let hash = hash_for("m", "Bucket", [ListOf(IntField)])

  // No list comprehension when the inner type is a passthrough primitive.
  let assert True =
    string.contains(out, "{'" <> hash <> "', F0}")
  let assert False =
    string.contains(out, "[_X1 || _X1 <- F0]")
}

// -- recursive type --------------------------------------------------------

pub fn recursive_type_emits_self_referencing_calls_test() {
  let tree_ref = UserType("m", "Tree", [])
  let dt =
    typ("m", "Tree", [
      variant("m", "Leaf", [IntField]),
      variant("m", "Node", [IntField, tree_ref, tree_ref]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])

  // Node's two recursive fields each call encode_m__tree on themselves.
  let assert True =
    string.contains(out, "encode_m__tree({node, F0, F1, F2}) ->")
  let assert True = string.contains(out, "encode_m__tree(F1)")
  let assert True = string.contains(out, "encode_m__tree(F2)")
}

// -- function names use qualified atoms (different modules, same name) -----

pub fn same_named_types_in_different_modules_get_distinct_function_names_test() {
  let dt_a =
    typ("admin/pages/discounts", "Discount", [
      variant("admin/pages/discounts", "Discount", [IntField]),
    ])
  let dt_b =
    typ("admin/pages/promos", "Discount", [
      variant("admin/pages/promos", "Discount", [IntField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt_a, dt_b])

  let assert True =
    string.contains(out, "encode_admin_pages_discounts__discount(")
  let assert True =
    string.contains(out, "encode_admin_pages_promos__discount(")
}

// -- TupleOf field --------------------------------------------------------

pub fn tuple_field_destructures_and_rebuilds_test() {
  let dt =
    typ("m", "Pair", [
      variant("m", "Pair", [TupleOf([IntField, UserType("m", "Item", [])])]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])

  // Tuple field destructures into per-position fresh vars, then rebuilds
  // applying encode_expr to each. Int passes through; user type recurses.
  let assert True =
    string.contains(out, "case F0 of {_T0_0, _T0_1} -> {_T0_0, encode_m__item(_T0_1)} end")
}

// -- BitArray / Nil pass through unchanged --------------------------------

pub fn bitarray_and_nil_pass_through_test() {
  let dt =
    typ("m", "Blob", [
      variant("m", "Blob", [BitArrayField, NilField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(module_name: "x_wire", discovered: [dt])
  let hash = hash_for("m", "Blob", [BitArrayField, NilField])

  let assert True =
    string.contains(out, "{'" <> hash <> "', F0, F1}")
}
