//// Tests for the per-consumer wire-transformers Erlang codegen.
////
//// Exact output shape is part of the wire-type-identity spec, but
//// these tests use targeted substring checks against the generated
//// source. That keeps them robust to whitespace and ordering changes
//// while still pinning the load-bearing properties: module shape,
//// per-type function pairs, hash-as-wire-tag, bare-atom-as-BEAM-tag,
//// float wrapping, list comprehensions, recursive cross-type calls.

import gleam/list
import gleam/option
import gleam/string
import libero/codegen_wire_erl
import libero/field_type.{
  BitArrayField, BoolField, DictOf, FloatField, IntField, ListOf, NilField,
  OptionOf, ResultOf, StringField, TupleOf, UserType,
}
import libero/scanner.{type HandlerEndpoint, HandlerEndpoint}
import libero/walker.{type DiscoveredType, DiscoveredType, DiscoveredVariant}
import libero/wire_identity

// -- fixtures --------------------------------------------------------------

fn variant(
  module_path: String,
  name: String,
  fields: List(field_type.FieldType),
) -> walker.DiscoveredVariant {
  DiscoveredVariant(
    module_path: module_path,
    variant_name: name,
    atom_name: walker.qualified_atom_name(
      module_path: module_path,
      variant_name: name,
    ),
    float_field_indices: [],
    field_labels: list.map(fields, fn(_) { option.None }),
    fields: fields,
  )
}

fn typ(
  module_path: String,
  name: String,
  variants: List(walker.DiscoveredVariant),
) -> DiscoveredType {
  DiscoveredType(
    module_path: module_path,
    type_name: name,
    type_params: [],
    variants: variants,
  )
}

fn hash_for(
  module_path: String,
  name: String,
  fields: List(field_type.FieldType),
) -> String {
  let #(_sig, hash) =
    wire_identity.wire_identity(
      module_path: module_path,
      constructor_name: name,
      fields: fields,
    )
  hash
}

// -- module shape ----------------------------------------------------------

pub fn empty_discovered_emits_module_with_only_float_helper_test() {
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [],
      push_dispatches: [],
    )
  let assert True = string.contains(out, "-module(x_wire).")
  let assert True = string.contains(out, "encode_float/1")
  let assert True = string.contains(out, "encode_float(F) when is_float(F)")
}

pub fn header_marks_generated_test() {
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [],
      push_dispatches: [],
    )
  let assert True =
    string.contains(out, "Code generated by libero. DO NOT EDIT.")
}

// -- single-variant record with primitives ---------------------------------

pub fn primitive_record_emits_encode_and_decode_test() {
  let dt =
    typ("shared/discount", "Discount", [
      variant("shared/discount", "Discount", [IntField, StringField, BoolField]),
    ])
  let hash =
    hash_for("shared/discount", "Discount", [IntField, StringField, BoolField])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  // Exports both directions for the type.
  let assert True = string.contains(out, "encode_shared_discount__discount/1")
  let assert True = string.contains(out, "decode_shared_discount__discount/1")

  // Encode clause: BEAM-shape pattern, wire-shape body.
  let assert True =
    string.contains(
      out,
      "encode_shared_discount__discount({discount, F0, F1, F2}) ->",
    )
  let assert True = string.contains(out, "{'" <> hash <> "', F0, F1, F2}")

  // Decode clause: wire-shape pattern, BEAM-shape body.
  let assert True =
    string.contains(
      out,
      "decode_shared_discount__discount({'" <> hash <> "', F0, F1, F2}) ->",
    )
  let assert True = string.contains(out, "{discount, F0, F1, F2}")
}

// -- float field wrapping (libero-3ccw regression) -------------------------

pub fn float_field_wraps_with_encode_float_on_encode_test() {
  let dt =
    typ("m", "Discount", [variant("m", "Discount", [IntField, FloatField])])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )
  let assert True = string.contains(out, "encode_float(F1)")
  // Decode side: Float passes through (BEAM ETF preserves Float natively).
  let assert True =
    string.contains(out, "decode_m__discount({'")
    && string.contains(out, ", F0, F1}) ->\n    {discount, F0, F1}")
}

// -- 0-arity variants ------------------------------------------------------

pub fn zero_arity_variant_emits_bare_atom_to_hash_test() {
  let dt =
    typ("shared/types", "Status", [
      variant("shared/types", "Pending", []),
      variant("shared/types", "Active", []),
    ])
  let pending_hash = hash_for("shared/types", "Pending", [])
  let active_hash = hash_for("shared/types", "Active", [])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  // Encode: bare atom -> hashed atom literal.
  let assert True =
    string.contains(
      out,
      "encode_shared_types__status(pending) ->\n    '" <> pending_hash <> "'",
    )
  let assert True =
    string.contains(
      out,
      "encode_shared_types__status(active) ->\n    '" <> active_hash <> "'",
    )

  // Decode: hashed atom literal -> bare atom.
  let assert True =
    string.contains(
      out,
      "decode_shared_types__status('" <> pending_hash <> "') ->\n    pending",
    )
}

// -- N-arity sum variants --------------------------------------------------

pub fn sum_type_n_arity_variants_emit_separate_clauses_test() {
  let dt =
    typ("m", "ItemError", [
      variant("m", "NotFound", [IntField]),
      variant("m", "InvalidState", [StringField]),
    ])
  let nf_hash = hash_for("m", "NotFound", [IntField])
  let is_hash = hash_for("m", "InvalidState", [StringField])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True =
    string.contains(
      out,
      "encode_m__item_error({not_found, F0}) ->\n    {'" <> nf_hash <> "', F0}",
    )
  let assert True =
    string.contains(
      out,
      "encode_m__item_error({invalid_state, F0}) ->\n    {'"
        <> is_hash
        <> "', F0}",
    )
}

// -- nested user types (envelope wrapping a List of records) ---------------

pub fn list_of_user_type_recurses_via_named_call_test() {
  let inner_type = UserType("admin/discounts", "Discount", [])
  let envelope_dt =
    typ("admin/discounts", "DiscountAdminData", [
      variant("admin/discounts", "DiscountAdminData", [ListOf(inner_type)]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [envelope_dt],
      endpoints: [],
      push_dispatches: [],
    )

  // Encode side: list comprehension wrapping the recursive call.
  let assert True =
    string.contains(out, "[encode_admin_discounts__discount(_X0) || _X0 <- F0]")
  // Decode side: same shape, decode_ instead of encode_.
  let assert True =
    string.contains(out, "[decode_admin_discounts__discount(_X0) || _X0 <- F0]")
}

// -- Option / Result containers --------------------------------------------

pub fn option_of_user_type_pattern_matches_some_none_test() {
  let inner = UserType("m", "Item", [])
  let dt = typ("m", "Wrapper", [variant("m", "Wrapper", [OptionOf(inner)])])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True =
    string.contains(
      out,
      "case F0 of {some, _X0} -> {some, encode_m__item(_X0)}; none -> none end",
    )
}

pub fn result_of_user_type_pattern_matches_ok_error_test() {
  let dt =
    typ("m", "Resp", [
      variant("m", "Resp", [
        ResultOf(ok: UserType("m", "Item", []), err: StringField),
      ]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True =
    string.contains(
      out,
      "case F0 of {ok, _X0} -> {ok, encode_m__item(_X0)}; {error, _E0} -> {error, _E0} end",
    )
}

// -- Dict (only values transform) ------------------------------------------

pub fn dict_with_user_value_transforms_only_values_test() {
  let dt =
    typ("m", "Index", [
      variant("m", "Index", [
        DictOf(key: StringField, value: UserType("m", "Item", [])),
      ]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True =
    string.contains(
      out,
      "maps:map(fun(_K, _X0) -> encode_m__item(_X0) end, F0)",
    )
}

// -- containers of primitives skip the transformation --------------------

pub fn list_of_int_passes_through_test() {
  let dt = typ("m", "Bucket", [variant("m", "Bucket", [ListOf(IntField)])])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )
  let hash = hash_for("m", "Bucket", [ListOf(IntField)])

  // No list comprehension when the inner type is a passthrough primitive.
  let assert True = string.contains(out, "{'" <> hash <> "', F0}")
  let assert False = string.contains(out, "[_X1 || _X1 <- F0]")
}

// -- recursive type --------------------------------------------------------

pub fn recursive_type_emits_self_referencing_calls_test() {
  let tree_ref = UserType("m", "Tree", [])
  let dt =
    typ("m", "Tree", [
      variant("m", "Leaf", [IntField]),
      variant("m", "Node", [IntField, tree_ref, tree_ref]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  // Node's two recursive fields each call encode_m__tree on themselves.
  let assert True =
    string.contains(out, "encode_m__tree({node, F0, F1, F2}) ->")
  let assert True = string.contains(out, "encode_m__tree(F1)")
  let assert True = string.contains(out, "encode_m__tree(F2)")
}

// -- function names use qualified atoms (different modules, same name) -----

pub fn same_named_types_in_different_modules_get_distinct_function_names_test() {
  let dt_a =
    typ("admin/pages/discounts", "Discount", [
      variant("admin/pages/discounts", "Discount", [IntField]),
    ])
  let dt_b =
    typ("admin/pages/promos", "Discount", [
      variant("admin/pages/promos", "Discount", [IntField, StringField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt_a, dt_b],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True =
    string.contains(out, "encode_admin_pages_discounts__discount(")
  let assert True = string.contains(out, "encode_admin_pages_promos__discount(")
}

pub fn same_named_same_arity_types_from_different_modules_succeed_test() {
  let dt_a =
    typ("waivers", "Waiver", [
      variant("waivers", "Waiver", [IntField, StringField]),
    ])
  let dt_b =
    typ("waivers/id_", "Waiver", [
      variant("waivers/id_", "Waiver", [IntField, StringField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt_a, dt_b],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True = string.contains(out, "encode_waivers__waiver(")
  let assert True = string.contains(out, "encode_waivers_id___waiver(")
  let hash_a = hash_for("waivers", "Waiver", [IntField, StringField])
  let hash_b = hash_for("waivers/id_", "Waiver", [IntField, StringField])
  let assert True = hash_a != hash_b
}

// -- TupleOf field --------------------------------------------------------

pub fn tuple_field_destructures_and_rebuilds_test() {
  let dt =
    typ("m", "Pair", [
      variant("m", "Pair", [TupleOf([IntField, UserType("m", "Item", [])])]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  // Tuple field destructures into per-position fresh vars, then rebuilds
  // applying encode_expr to each. Int passes through; user type recurses.
  let assert True =
    string.contains(
      out,
      "case F0 of {_T0_0, _T0_1} -> {_T0_0, encode_m__item(_T0_1)} end",
    )
}

// -- BitArray / Nil pass through unchanged --------------------------------

pub fn bitarray_and_nil_pass_through_test() {
  let dt =
    typ("m", "Blob", [
      variant("m", "Blob", [BitArrayField, NilField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )
  let hash = hash_for("m", "Blob", [BitArrayField, NilField])

  let assert True = string.contains(out, "{'" <> hash <> "', F0, F1}")
}

// -- encode_term / decode_term generic walkers ----------------------------

pub fn encode_term_and_decode_term_exported_test() {
  let dt =
    typ("m", "Item", [
      variant("m", "Item", [StringField, IntField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True = string.contains(out, "encode_term/1")
  let assert True = string.contains(out, "decode_term/1")
}

pub fn encode_term_does_not_dispatch_zero_arity_variants_test() {
  let dt =
    typ("shared/types", "Status", [
      variant("shared/types", "Pending", []),
      variant("shared/types", "Active", []),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert False = string.contains(out, "pending -> '")
  let assert False = string.contains(out, "active -> '")
  let assert True = string.contains(out, "encode_term(Other, _Depth) -> Other")
}

pub fn encode_term_does_not_dispatch_n_arity_variants_test() {
  let dt =
    typ("m", "Item", [
      variant("m", "Item", [StringField, IntField, BoolField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert False = string.contains(out, "{item, 4} -> encode_m__item(Tuple)")
  let assert True =
    string.contains(
      out,
      "encode_term(Tuple, Depth) when is_tuple(Tuple), tuple_size(Tuple) > 0",
    )
}

pub fn decode_term_maps_hashed_atoms_for_zero_arity_variants_test() {
  let pending_hash = hash_for("shared/types", "Pending", [])
  let active_hash = hash_for("shared/types", "Active", [])
  let dt =
    typ("shared/types", "Status", [
      variant("shared/types", "Pending", []),
      variant("shared/types", "Active", []),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True = string.contains(out, "'" <> pending_hash <> "' -> pending")
  let assert True = string.contains(out, "'" <> active_hash <> "' -> active")
}

pub fn decode_term_matches_hash_and_arity_for_n_arity_variants_test() {
  let item_hash = hash_for("m", "Item", [StringField, IntField, BoolField])
  let dt =
    typ("m", "Item", [
      variant("m", "Item", [StringField, IntField, BoolField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt],
      endpoints: [],
      push_dispatches: [],
    )

  let assert True =
    string.contains(out, "{'" <> item_hash <> "', 4} -> decode_m__item(Tuple)")
}

pub fn encode_term_is_container_only_with_mixed_types_test() {
  let dt_status =
    typ("m", "Status", [
      variant("m", "Pending", []),
      variant("m", "Active", []),
    ])
  let dt_item =
    typ("m", "Item", [
      variant("m", "Item", [StringField, IntField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt_status, dt_item],
      endpoints: [],
      push_dispatches: [],
    )

  let assert False = string.contains(out, "pending -> '")
  let assert False = string.contains(out, "{item, 3} -> encode_m__item(Tuple)")
  let assert True =
    string.contains(out, "encode_term(List, Depth) when is_list")
  let assert True = string.contains(out, "encode_term(Map, Depth) when is_map")
}

// -- duplicate variant regression -------------------------------------------

pub fn duplicate_zero_arity_across_modules_typed_encoders_distinct_test() {
  let dt_a =
    typ("pages/a", "Category", [
      variant("pages/a", "Identity", []),
      variant("pages/a", "Contact", []),
    ])
  let dt_b =
    typ("pages/b", "Category", [
      variant("pages/b", "Identity", []),
      variant("pages/b", "Contact", []),
    ])
  let hash_a = hash_for("pages/a", "Identity", [])
  let hash_b = hash_for("pages/b", "Identity", [])
  let assert True = hash_a != hash_b

  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt_a, dt_b],
      endpoints: [],
      push_dispatches: [],
    )

  // Per-type encoders produce distinct hashes for same constructor name
  let assert True =
    string.contains(
      out,
      "encode_pages_a__category(identity) ->\n    '" <> hash_a <> "'",
    )
  let assert True =
    string.contains(
      out,
      "encode_pages_b__category(identity) ->\n    '" <> hash_b <> "'",
    )

  // encode_term does NOT contain any atom-to-hash dispatch
  let assert False = string.contains(out, "identity -> '")
}

pub fn duplicate_zero_arity_decode_term_handles_both_hashes_test() {
  let dt_a =
    typ("pages/a", "Category", [
      variant("pages/a", "Identity", []),
    ])
  let dt_b =
    typ("pages/b", "Category", [
      variant("pages/b", "Identity", []),
    ])
  let hash_a = hash_for("pages/a", "Identity", [])
  let hash_b = hash_for("pages/b", "Identity", [])

  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt_a, dt_b],
      endpoints: [],
      push_dispatches: [],
    )

  // decode_term maps BOTH hashes back to the same bare atom
  let assert True = string.contains(out, "'" <> hash_a <> "' -> identity")
  let assert True = string.contains(out, "'" <> hash_b <> "' -> identity")
}

pub fn duplicate_n_arity_across_modules_no_encode_term_dispatch_test() {
  let dt_a =
    typ("pages/a", "Item", [
      variant("pages/a", "Item", [StringField, IntField]),
    ])
  let dt_b =
    typ("pages/b", "Item", [
      variant("pages/b", "Item", [StringField, IntField]),
    ])
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [dt_a, dt_b],
      endpoints: [],
      push_dispatches: [],
    )

  // encode_term has no constructor dispatch at all
  let assert False = string.contains(out, "{item, 3} -> encode_")

  // But per-type encoders exist and are distinct
  let assert True = string.contains(out, "encode_pages_a__item({item,")
  let assert True = string.contains(out, "encode_pages_b__item({item,")

  // decode_term routes by hash (unique), both present
  let hash_a = hash_for("pages/a", "Item", [StringField, IntField])
  let hash_b = hash_for("pages/b", "Item", [StringField, IntField])
  let assert True =
    string.contains(out, "{'" <> hash_a <> "', 3} -> decode_pages_a__item")
  let assert True =
    string.contains(out, "{'" <> hash_b <> "', 3} -> decode_pages_b__item")
}

// -- decode_client_msg -------------------------------------------------------

fn endpoint(
  fn_name: String,
  params: List(#(String, field_type.FieldType)),
  return_ok: field_type.FieldType,
  return_err: field_type.FieldType,
) -> HandlerEndpoint {
  HandlerEndpoint(
    module_path: "handlers/" <> fn_name,
    fn_name:,
    return_ok:,
    return_err:,
    params:,
    mutates_context: False,
    msg_type: option.None,
  )
}

fn endpoint_with_msg_type(
  fn_name: String,
  params: List(#(String, field_type.FieldType)),
  msg_module: String,
  msg_constructor: String,
) -> HandlerEndpoint {
  let ep = endpoint(fn_name, params, NilField, NilField)
  HandlerEndpoint(..ep, msg_type: option.Some(#(msg_module, msg_constructor)))
}

pub fn decode_client_msg_zero_arity_endpoint_passes_bare_atom_test() {
  let ep = endpoint("load_discounts", [], NilField, NilField)
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let assert True = string.contains(out, "decode_client_msg/1")
  let assert True =
    string.contains(
      out,
      "decode_client_msg(server_load_discounts) ->\n    server_load_discounts",
    )
  let assert True =
    string.contains(out, "decode_client_msg(Other) ->\n    Other")
}

pub fn decode_client_msg_zero_arity_msg_type_accepts_wire_hash_test() {
  let ep =
    endpoint_with_msg_type(
      "load_sponsors",
      [],
      "admin/pages/website/sponsors",
      "ServerLoadSponsors",
    )
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let hash =
    hash_for("admin/pages/website/sponsors", "ServerLoadSponsors", [])
  let assert True =
    string.contains(
      out,
      "decode_client_msg('" <> hash <> "') ->\n    server_load_sponsors",
    )
  let assert True =
    string.contains(
      out,
      "decode_client_msg(server_load_sponsors) ->\n    server_load_sponsors",
    )
}

pub fn decode_client_msg_user_type_param_calls_decoder_test() {
  let item_type = UserType("shared_types", "Item", [])
  let ep = endpoint("echo_item", [#("item", item_type)], item_type, NilField)
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let assert True =
    string.contains(
      out,
      "decode_client_msg({server_echo_item, F0}) ->\n    {server_echo_item, decode_shared_types__item(F0)}",
    )
}

pub fn decode_client_msg_mixed_primitive_and_user_type_params_test() {
  let discount_type = UserType("admin/discounts", "DiscountParams", [])
  let ep =
    endpoint(
      "update_discount",
      [#("id", IntField), #("params", discount_type)],
      NilField,
      NilField,
    )
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let assert True =
    string.contains(
      out,
      "decode_client_msg({server_update_discount, F0, F1}) ->\n    {server_update_discount, F0, decode_admin_discounts__discount_params(F1)}",
    )
}

pub fn decode_client_msg_param_msg_type_accepts_wire_hash_test() {
  let params_type = UserType("admin/sponsors", "SponsorParams", [])
  let ep =
    endpoint_with_msg_type(
      "update_sponsor",
      [#("id", IntField), #("params", params_type)],
      "admin/sponsors",
      "ServerUpdateSponsor",
    )
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let hash =
    hash_for(
      "admin/sponsors",
      "ServerUpdateSponsor",
      [IntField, params_type],
    )
  let expected =
    "decode_client_msg({'" <> hash <> "', F0, F1}) ->\n    {server_update_sponsor, F0, decode_admin_sponsors__sponsor_params(F1)}"
  let assert True = string.contains(out, expected)
}

pub fn decode_client_msg_list_of_user_type_param_test() {
  let item_type = UserType("m", "Item", [])
  let ep =
    endpoint("batch", [#("items", ListOf(item_type))], NilField, NilField)
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let assert True =
    string.contains(
      out,
      "decode_client_msg({server_batch, F0}) ->\n    {server_batch, [decode_m__item(_X0) || _X0 <- F0]}",
    )
}

pub fn decode_client_msg_not_exported_when_no_endpoints_test() {
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [],
      push_dispatches: [],
    )

  let assert False = string.contains(out, "decode_client_msg")
}

// -- encode_response_<fn> ----------------------------------------------------

pub fn encode_response_user_type_ok_and_err_test() {
  let item_type = UserType("shared_types", "Item", [])
  let err_type = UserType("m", "ItemError", [])
  let ep = endpoint("echo_item", [#("item", item_type)], item_type, err_type)
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let assert True = string.contains(out, "encode_response_echo_item/1")
  let assert True =
    string.contains(
      out,
      "encode_response_echo_item({ok, V}) ->\n    {ok, encode_shared_types__item(V)}",
    )
  let assert True =
    string.contains(
      out,
      "encode_response_echo_item({error, E}) ->\n    {error, encode_m__item_error(E)}",
    )
}

pub fn encode_response_primitive_ok_and_nil_err_passthrough_test() {
  let ep = endpoint("get_count", [], IntField, NilField)
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let assert True = string.contains(out, "encode_response_get_count/1")
  let assert True =
    string.contains(out, "encode_response_get_count({ok, V}) ->\n    {ok, V}")
  let assert True =
    string.contains(
      out,
      "encode_response_get_count({error, E}) ->\n    {error, E}",
    )
}

pub fn encode_response_list_of_user_type_ok_test() {
  let item_type = UserType("m", "Item", [])
  let ep = endpoint("list_items", [], ListOf(item_type), NilField)
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )

  let assert True =
    string.contains(
      out,
      "encode_response_list_items({ok, V}) ->\n    {ok, [encode_m__item(_X0) || _X0 <- V]}",
    )
}

pub fn endpoint_param_with_bad_dict_key_rejected_test() {
  let bad_param = DictOf(UserType("m", "Item", []), IntField)
  let ep = endpoint("bad", [#("data", bad_param)], NilField, NilField)
  let assert Error(_) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )
}

pub fn endpoint_return_ok_with_bad_dict_key_rejected_test() {
  let bad_return = DictOf(UserType("m", "Item", []), IntField)
  let ep = endpoint("bad", [], bad_return, NilField)
  let assert Error(_) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [
        ep,
      ],
      push_dispatches: [],
    )
}

pub fn encode_response_not_exported_when_no_endpoints_test() {
  let assert Ok(out) =
    codegen_wire_erl.generate(
      module_name: "x_wire",
      discovered: [],
      endpoints: [],
      push_dispatches: [],
    )

  let assert False = string.contains(out, "encode_response_")
}

// -- behavioral dispatch boundary tests (same-name/same-arity) ---------------

@external(erlang, "libero_ffi", "compile_module_from_source")
fn compile_module(source: String) -> Result(atom, Nil)

@external(erlang, "erlang", "apply")
fn erl_apply(module: atom, function: atom, args: List(a)) -> b

@external(erlang, "libero_test_ffi", "apply2")
fn erl_apply2(module: atom, function: atom, arg1: a, arg2: b) -> c

@external(erlang, "erlang", "binary_to_atom")
fn binary_to_atom(name: String) -> atom

pub fn decode_client_msg_routes_to_correct_decoder_for_same_name_types_test() {
  let waiver_a_type = UserType("waivers", "Waiver", [])
  let waiver_b_type = UserType("waivers/id_", "Waiver", [])
  let dt_a =
    typ("waivers", "Waiver", [
      variant("waivers", "Waiver", [IntField, StringField]),
    ])
  let dt_b =
    typ("waivers/id_", "Waiver", [
      variant("waivers/id_", "Waiver", [IntField, StringField]),
    ])
  let ep_a =
    endpoint("use_waiver_a", [#("w", waiver_a_type)], NilField, NilField)
  let ep_b =
    endpoint("use_waiver_b", [#("w", waiver_b_type)], NilField, NilField)

  let assert Ok(source) =
    codegen_wire_erl.generate(
      module_name: "boundary_decode_test",
      discovered: [dt_a, dt_b],
      endpoints: [ep_a, ep_b],
      push_dispatches: [],
    )
  let assert Ok(mod) = compile_module(source)

  let hash_a = hash_for("waivers", "Waiver", [IntField, StringField])
  let hash_b = hash_for("waivers/id_", "Waiver", [IntField, StringField])
  let assert True = hash_a != hash_b

  let wire_msg_a: #(atom, #(atom, Int, String)) =
    erl_apply(mod, binary_to_atom("decode_client_msg"), [
      #(
        binary_to_atom("server_use_waiver_a"),
        #(binary_to_atom(hash_a), 1, "name"),
      ),
    ])
  let assert #(_, #(tag_a, 1, "name")) = wire_msg_a
  let assert True = tag_a == binary_to_atom("waiver")

  let wire_msg_b: #(atom, #(atom, Int, String)) =
    erl_apply(mod, binary_to_atom("decode_client_msg"), [
      #(
        binary_to_atom("server_use_waiver_b"),
        #(binary_to_atom(hash_b), 1, "name"),
      ),
    ])
  let assert #(_, #(tag_b, 1, "name")) = wire_msg_b
  let assert True = tag_b == binary_to_atom("waiver")
}

pub fn encode_response_uses_correct_encoder_for_same_name_types_test() {
  let waiver_a_type = UserType("waivers", "Waiver", [])
  let waiver_b_type = UserType("waivers/id_", "Waiver", [])
  let dt_a =
    typ("waivers", "Waiver", [
      variant("waivers", "Waiver", [IntField, StringField]),
    ])
  let dt_b =
    typ("waivers/id_", "Waiver", [
      variant("waivers/id_", "Waiver", [IntField, StringField]),
    ])
  let ep_a = endpoint("get_waiver_a", [], waiver_a_type, NilField)
  let ep_b = endpoint("get_waiver_b", [], waiver_b_type, NilField)

  let assert Ok(source) =
    codegen_wire_erl.generate(
      module_name: "boundary_encode_test",
      discovered: [dt_a, dt_b],
      endpoints: [ep_a, ep_b],
      push_dispatches: [],
    )
  let assert Ok(mod) = compile_module(source)

  let hash_a = hash_for("waivers", "Waiver", [IntField, StringField])
  let hash_b = hash_for("waivers/id_", "Waiver", [IntField, StringField])

  let result_a: #(atom, #(atom, Int, String)) =
    erl_apply(mod, binary_to_atom("encode_response_get_waiver_a"), [
      #(binary_to_atom("ok"), #(binary_to_atom("waiver"), 1, "alice")),
    ])
  let assert #(_, #(wire_tag_a, 1, "alice")) = result_a
  let assert True = wire_tag_a == binary_to_atom(hash_a)

  let result_b: #(atom, #(atom, Int, String)) =
    erl_apply(mod, binary_to_atom("encode_response_get_waiver_b"), [
      #(binary_to_atom("ok"), #(binary_to_atom("waiver"), 2, "bob")),
    ])
  let assert #(_, #(wire_tag_b, 2, "bob")) = result_b
  let assert True = wire_tag_b == binary_to_atom(hash_b)
  let assert True = wire_tag_a != wire_tag_b
}

pub fn encode_push_not_emitted_when_no_dispatches_test() {
  let result =
    codegen_wire_erl.generate(
      module_name: "test_wire",
      discovered: [],
      endpoints: [],
      push_dispatches: [],
    )
  let assert Ok(source) = result
  let assert False = string.contains(source, "encode_push")
}

pub fn encode_push_dispatches_to_typed_encoder_test() {
  let discovered = [
    typ("pages/home", "ToClient", [
      variant("pages/home", "DataLoaded", [StringField]),
    ]),
  ]
  let result =
    codegen_wire_erl.generate(
      module_name: "test_wire",
      discovered: discovered,
      endpoints: [],
      push_dispatches: [
        codegen_wire_erl.PushDispatch(
          page_tag: "Home",
          type_atom: "pages_home__to_client",
        ),
      ],
    )
  let assert Ok(source) = result
  let assert True = string.contains(source, "encode_push(<<\"Home\">>, Msg)")
  let assert True = string.contains(source, "encode_pages_home__to_client(Msg)")
  let assert True = string.contains(source, "encode_push/2")
  let assert True = string.contains(source, "error({no_push_encoder, Page})")
}

pub fn encode_push_multiple_pages_and_client_context_test() {
  let discovered = [
    typ("pages/home", "ToClient", [variant("pages/home", "Refreshed", [])]),
    typ("pages/settings", "ToClient", [
      variant("pages/settings", "Saved", []),
    ]),
    typ("client_context", "ClientContextMsg", [
      variant("client_context", "SignedIn", [StringField]),
    ]),
  ]
  let result =
    codegen_wire_erl.generate(
      module_name: "test_wire",
      discovered: discovered,
      endpoints: [],
      push_dispatches: [
        codegen_wire_erl.PushDispatch(
          page_tag: "Home",
          type_atom: "pages_home__to_client",
        ),
        codegen_wire_erl.PushDispatch(
          page_tag: "Settings",
          type_atom: "pages_settings__to_client",
        ),
        codegen_wire_erl.PushDispatch(
          page_tag: "__ClientContext__",
          type_atom: "client_context__client_context_msg",
        ),
      ],
    )
  let assert Ok(source) = result
  let assert True = string.contains(source, "encode_push(<<\"Home\">>, Msg)")
  let assert True =
    string.contains(source, "encode_push(<<\"Settings\">>, Msg)")
  let assert True =
    string.contains(source, "encode_push(<<\"__ClientContext__\">>, Msg)")
  let assert True =
    string.contains(source, "encode_client_context__client_context_msg(Msg)")
}

pub fn encode_push_routes_to_correct_encoder_for_duplicate_variants_test() {
  let dt_a =
    typ("pages/dashboard", "ToClient", [
      variant("pages/dashboard", "Updated", [StringField]),
    ])
  let dt_b =
    typ("pages/reports", "ToClient", [
      variant("pages/reports", "Updated", [StringField]),
    ])

  let assert Ok(source) =
    codegen_wire_erl.generate(
      module_name: "boundary_push_test",
      discovered: [dt_a, dt_b],
      endpoints: [],
      push_dispatches: [
        codegen_wire_erl.PushDispatch(
          page_tag: "Dashboard",
          type_atom: "pages_dashboard__to_client",
        ),
        codegen_wire_erl.PushDispatch(
          page_tag: "Reports",
          type_atom: "pages_reports__to_client",
        ),
      ],
    )
  let assert Ok(mod) = compile_module(source)

  let hash_a = hash_for("pages/dashboard", "Updated", [StringField])
  let hash_b = hash_for("pages/reports", "Updated", [StringField])
  let assert True = hash_a != hash_b

  let result_a: #(atom, String) =
    erl_apply2(mod, binary_to_atom("encode_push"), "Dashboard", #(
      binary_to_atom("updated"),
      "payload_a",
    ))
  let assert #(wire_tag_a, "payload_a") = result_a
  let assert True = wire_tag_a == binary_to_atom(hash_a)

  let result_b: #(atom, String) =
    erl_apply2(mod, binary_to_atom("encode_push"), "Reports", #(
      binary_to_atom("updated"),
      "payload_b",
    ))
  let assert #(wire_tag_b, "payload_b") = result_b
  let assert True = wire_tag_b == binary_to_atom(hash_b)
  let assert True = wire_tag_a != wire_tag_b
}
