//// Integration test for the dispatch panic-catching pattern.
////
//// Verifies that the pattern generated by codegen_dispatch
//// (trace.try_call wrapping a handler, encoding InternalError on
//// panic) produces the correct wire response at runtime.

import gleam/string
import libero/error.{type RpcError, InternalError}
import libero/trace
import libero/wire

pub fn panicking_handler_produces_internal_error_test() {
  let request_id = 1
  let response = case trace.try_call(fn() { panic as "handler exploded" }) {
    Ok(result) -> wire.tag_response(request_id:, data: wire.encode(Ok(result)))
    Error(reason) -> {
      let trace_id = trace.new_trace_id()
      let _ = reason
      wire.tag_response(
        request_id:,
        data: wire.encode(
          Error(InternalError(trace_id:, message: "Something went wrong")),
        ),
      )
    }
  }
  let assert <<0, 0, 0, 0, 1, payload:bits>> = response
  let result: Result(Nil, RpcError) = wire.decode(payload)
  let assert Error(InternalError(trace_id:, message: "Something went wrong")) =
    result
  let assert True = string.length(trace_id) > 0
}

pub fn successful_handler_produces_ok_response_test() {
  let request_id = 42
  let response = case trace.try_call(fn() { Ok(123) }) {
    Ok(result) -> wire.tag_response(request_id:, data: wire.encode(result))
    Error(reason) -> {
      let trace_id = trace.new_trace_id()
      let _ = reason
      wire.tag_response(
        request_id:,
        data: wire.encode(
          Error(InternalError(trace_id:, message: "Something went wrong")),
        ),
      )
    }
  }
  let assert <<0, 0, 0, 0, 42, payload:bits>> = response
  let result: Result(Int, RpcError) = wire.decode(payload)
  let assert Ok(123) = result
}

pub fn mutating_handler_panic_preserves_original_context_test() {
  let original_ctx = "original"
  let #(response, ctx) = case
    trace.try_call(fn() { #(Ok(42), "mutated_ctx") })
  {
    Ok(#(result, new_ctx)) -> #(
      wire.tag_response(request_id: 1, data: wire.encode(result)),
      new_ctx,
    )
    Error(reason) -> {
      let trace_id = trace.new_trace_id()
      let _ = reason
      #(
        wire.tag_response(
          request_id: 1,
          data: wire.encode(
            Error(InternalError(trace_id:, message: "Something went wrong")),
          ),
        ),
        original_ctx,
      )
    }
  }
  let assert "mutated_ctx" = ctx
  let assert <<0, 0, 0, 0, 1, payload:bits>> = response
  let result: Result(Int, RpcError) = wire.decode(payload)
  let assert Ok(42) = result
}

pub fn mutating_handler_panic_returns_original_context_test() {
  let original_ctx = "original"
  let #(response, ctx) = case
    trace.try_call(fn() {
      panic as "crashed during mutation"
      #(Ok(42), "should_not_reach")
    })
  {
    Ok(#(result, new_ctx)) -> #(
      wire.tag_response(request_id: 1, data: wire.encode(result)),
      new_ctx,
    )
    Error(reason) -> {
      let trace_id = trace.new_trace_id()
      let _ = reason
      #(
        wire.tag_response(
          request_id: 1,
          data: wire.encode(
            Error(InternalError(trace_id:, message: "Something went wrong")),
          ),
        ),
        original_ctx,
      )
    }
  }
  let assert "original" = ctx
  let assert <<0, 0, 0, 0, 1, payload:bits>> = response
  let result: Result(Nil, RpcError) = wire.decode(payload)
  let assert Error(InternalError(trace_id:, message: "Something went wrong")) =
    result
  let assert True = string.length(trace_id) > 0
}
